### ISSUE TITLE
AirbreakTeleport.inc - Incorrect detection

### ISSUE THREAD

**Issue by valenda-s** [RogueDrifter/Anti_cheat_pack#19]
**Describe the bug**
Sometimes _(not always)_, AirbreakTeleport.inc is triggered when players leave our Duel arena, and get put back in world 0. The Duel arena world ID is 1000, and uses the Warehouse 1 interior.

[14:21:06] Duel: PlayerA(14) won a duel against PlayerB(6).
[14:21:07] [AC] Possible hacker PlayerA(14) using Airbrake/TP hacks!

**To Reproduce**
It cannot be reliably reproduced, it happens at random, my guess would be down due to client lag.

**Expected behavior**
I expected AirbreakTeleport.inc to _not_ be triggered.

**Screenshots**
I would share screenshots or a video, but when it happens at random, it's one of those things that cannot really be recorded.

**Samp details (please complete the following information):**
 - Version: Linux 0.3.7-R2. The client who triggered the warning in the example above is running 0.3.7 (not R2, R3 or R4).
 - Using filterscripts? Yes
 - Using sampctl? No

**Additional context**
N/A

**Comment by valenda-s** [comment]
Sorry, I didn't think to try https://github.com/RogueDrifter/Anti_cheat_pack/blob/master/Anti-Cheat/LaggersDetect.inc since from what I understand, this may help reduce false-positives when running with AirbreakTeleport.inc for laggy clients.

I'll try that and see what happens.

**Comment by RogueDrifter** [comment]
Yes please do use that but make sure LaggersDetect is included before the airbreak include, and report back to me, also, could you provide more information on what happens when duel finishes? Which player is being detected as cheater? A player who died? Or the player who won? And does the player who won get teleported?

What changes happen? Is it only virtual world? Or does interior also change and does position also change? 

Meanwhile you could also use the parameters of the function so we can know exactly which part of code triggered the detection, print out the full function parameters, like so:
```
public OnPlayerBreakAir(playerid, breaktype)
{
    printf("playerid %d breaktype %d");
    return 1;
}
```

breaktype will help us know which part of the script was the reason.

**Comment by RogueDrifter** [comment]
Issue was fixed using the laggers include
