### ISSUE TITLE
AC Teleport

### ISSUE THREAD

**Issue by Olegka35** [RogueDrifter/Anti_cheat_pack#4]
Hello all!
I have a question
Install your OPBA anticheat - airbreak is detected.
But not teleport

I began to debug a code and noticed than after **SetTimerEx("OPBA_CheckRealTP"...)** in the end of **OPBA_AirbrakeTeleport** coordinates are rewrited. So in **OPBA_CheckRealTP** we have cheated coordinates, not fair.

Don't we have to add any condition to **GetPlayerPos(playerid, OPBA_Player[playerid][RacX], OPBA_Player[playerid][RacY], OPBA_Player[playerid][RacZ]);** in the end of **OPBA_AirbrakeTeleport** which will prevent it in case if **OPBA_Player[playerid][RacHoldCheck] == true**? 

Thanks
Sorry for my English.

**Comment by RogueDrifter** [comment]
Wow genius you are absolutely right!!! i can't believe i missed this thank you very much! fixed :+1: 

In case if you are wondering why i do a (Check Real TP) it's because when players go into samp built in interiors the fact that the simple delays caused false detections so i had to hold back all teleport detections for a couple of seconds to see if the interior changed or not (since sometimes position is set first before interior with delays).

The code sadly has gone too complicated and crowded that i started missing things, i apologize for that.
