### ISSUE TITLE
OPBA AntiCheat

### ISSUE THREAD

**Issue by Olegka35** [RogueDrifter/Anti_cheat_pack#5]
Hello once again

In OPBA.inc you create a timer for every connected players with deley in 300 ms. 
Don't you test whis ac with some more delay? 
I think it is very hard load on servers with big online, doesn't it?

And what if we create one timer (with foreach) instead of many of them? 

Thank you for answers

**Comment by RogueDrifter** [comment]
About the one foreach timer instead of many timers: http://forum.sa-mp.com/showthread.php?t=643553

Also, about the delay, 300ms couldn't go lower, if you do go lower than 300ms (for servers with many players) the position will be reset too fast that it will not detect airbreak and will HARDLY detect teleport (i know so because i have tried myself).

I think it shouldn't cause problems if your code is clean and isn't heavyloading your own server, also hey you can even edit it yourself if you have any problems and report back to me.

If you have any more inquiries feel free to message me on my discord @ Andy[RDZ]#0040
